In [1]:
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\HP\Desktop\Data Sets\googleplaystore.csv")
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [8]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [9]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [11]:
df.shape

(10841, 13)

In [15]:
df1 = df.query("Rating >= 4.5")

In [16]:
df1.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up

In [18]:
df2 = df1.sort_values("Rating")
df2

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device
6534,New York Mysteries (Full),GAME,4.5,514,5.9M,"5,000+",Paid,$6.99,Teen,Adventure,"June 4, 2018",1.0.36,4.0 and up
6543,Bangla Calendar 1425: (EN-BN-AR) Holiday,LIFESTYLE,4.5,31,2.3M,"1,000+",Free,0,Everyone,Lifestyle,"April 21, 2018",2.1.0,4.1 and up
6550,Bubble Bo-Bo,FAMILY,4.5,65,24M,"10,000+",Free,0,Everyone,Casual,"July 5, 2018",6.0,4.0 and up
6551,Boom Beach,FAMILY,4.5,5591653,95M,"50,000,000+",Free,0,Everyone 10+,Strategy,"July 18, 2018",35.119,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9806,Dr. ES PV Calculator,TOOLS,5.0,19,11M,500+,Free,0,Everyone,Tools,"March 11, 2018",3.4.7.2.16,4.1 and up
7533,Color CL,LIFESTYLE,5.0,2,1.3M,100+,Free,0,Everyone,Lifestyle,"February 2, 2017",1.01,4.0.3 and up
7482,Tic Tac CK,FAMILY,5.0,3,13M,10+,Free,0,Everyone,Puzzle,"July 3, 2018",1.0,4.0.3 and up
7477,USMLE Step 2 CK Flashcards,FAMILY,5.0,1,40M,10+,Paid,$19.99,Everyone,Education,"May 26, 2014",2.47,2.2 and up
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [19]:
df2.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9806,Dr. ES PV Calculator,TOOLS,5.0,19,11M,500+,Free,0,Everyone,Tools,"March 11, 2018",3.4.7.2.16,4.1 and up
7533,Color CL,LIFESTYLE,5.0,2,1.3M,100+,Free,0,Everyone,Lifestyle,"February 2, 2017",1.01,4.0.3 and up
7482,Tic Tac CK,FAMILY,5.0,3,13M,10+,Free,0,Everyone,Puzzle,"July 3, 2018",1.0,4.0.3 and up
7477,USMLE Step 2 CK Flashcards,FAMILY,5.0,1,40M,10+,Paid,$19.99,Everyone,Education,"May 26, 2014",2.47,2.2 and up
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [21]:
df2.query("Rating>5")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [23]:
df.sample(15)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
971,Viki: Asian TV Dramas & Movies,ENTERTAINMENT,4.3,407719,Varies with device,"10,000,000+",Free,0,Teen,Entertainment,"July 27, 2018",Varies with device,Varies with device
4797,Talking Tom & Ben News,FAMILY,4.4,1131937,41M,"100,000,000+",Free,0,Everyone,Entertainment,"April 30, 2018",2.4.0.7,4.1 and up
2841,Photo Collage - Layout Editor,PHOTOGRAPHY,4.5,285788,46M,"10,000,000+",Free,0,Everyone,Photography,"December 4, 2017",1.8.0.170824_9,5.0 - 8.0
5123,Ag PhD Soybean Diseases,BOOKS_AND_REFERENCE,NaN,0,5.9M,"1,000+",Free,0,Everyone,Books & Reference,"May 8, 2017",1.0.3,4.0.3 and up
2479,high cholesterol levels,MEDICAL,NaN,0,3.3M,100+,Free,0,Everyone,Medical,"July 23, 2018",1.0,4.1 and up
2870,InstaSize Photo Filters & Collage Editor,PHOTOGRAPHY,4.3,811693,50M,"50,000,000+",Free,0,Everyone,Photography,"August 2, 2018",4.0.26,4.4 and up
4190,H*nest Meditation,LIFESTYLE,4.9,145,48M,"5,000+",Paid,$1.99,Mature 17+,Lifestyle,"April 7, 2016",1.0,4.0.3 and up
2619,Timehop,SOCIAL,4.1,161610,16M,"5,000,000+",Free,0,Teen,Social,"August 5, 2018",4.5.3,4.1 and up
2944,"Candy Camera - selfie, beauty camera, photo ed...",PHOTOGRAPHY,4.4,3368705,Varies with device,"100,000,000+",Free,0,Everyone,Photography,"July 16, 2018",4.47,4.0.3 and up
7439,CJ Wilson's ZoomZoomnation,PRODUCTIVITY,4.0,4,8.2M,500+,Free,0,Everyone,Productivity,"July 11, 2018",3.5.3,4.0.3 and up
7914,Public Service CU Mobile,FINANCE,2.0,314,35M,"10,000+",Free,0,Everyone,Finance,"March 14, 2017",6.5.32-prod,4.2 and up
4935,Hi-Smart AC,TOOLS,2.2,32,9.4M,"1,000+",Free,0,Everyone,Tools,"April 3, 2018",1.1.0,4.4 and up
1738,Pixel Art: Color by Number Game,GAME,4.7,1125017,25M,"10,000,000+",Free,0,Everyone,Puzzle,"July 17, 2018",3.9.2,4.3 and up
4611,AT&T Call Protect,COMMUNICATION,4.2,6454,15M,"5,000,000+",Free,0,Everyone,Communication,"May 3, 2018",1.5.13-3598,5.0 and up
7786,DCUO|CR Calculator Lite,TOOLS,4.0,182,1.7M,"10,000+",Free,0,Everyone,Tools,"August 14, 2017",3.3,3.0 and up

In [26]:
df.shape

(10841, 13)

In [27]:
df3 = df.dropna()
df3.shape

(9360, 13)

In [31]:
d = df3.groupby("Genres").mean("Rating")
d

                                         Rating
Genres
Action                                 4.285475
Action;Action & Adventure              4.311765
Adventure                              4.180822
Adventure;Action & Adventure           4.423077
Adventure;Brain Games                  4.600000
...                                         ...
Video Players & Editors                4.063924
Video Players & Editors;Creativity     4.100000
Video Players & Editors;Music & Video  4.000000
Weather                                4.244000
Word                                   4.410714

[115 rows x 1 columns]

In [32]:
d.tail()

                                         Rating
Genres
Video Players & Editors                4.063924
Video Players & Editors;Creativity     4.100000
Video Players & Editors;Music & Video  4.000000
Weather                                4.244000
Word                                   4.410714

In [34]:
df3.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

In [37]:
pivot = pd.pivot_table(columns = 'Genres',
                      values = 'Rating',
                      data = df3, aggfunc = "mean")
pivot

Genres,Action,Action;Action & Adventure,Adventure,Adventure;Action & Adventure,Adventure;Brain Games,Adventure;Education,Arcade,Arcade;Action & Adventure,Arcade;Pretend Play,Art & Design,...,Tools,Tools;Education,Travel & Local,Travel & Local;Action & Adventure,Trivia,Video Players & Editors,Video Players & Editors;Creativity,Video Players & Editors;Music & Video,Weather,Word
Rating,4.285475,4.311765,4.180822,4.423077,4.6,4.1,4.304348,4.346667,4.5,4.38,...,4.046585,4.5,4.109333,4.1,4.039286,4.063924,4.1,4.0,4.244,4.410714

In [38]:
pivot.transpose()

                                         Rating
Genres
Action                                 4.285475
Action;Action & Adventure              4.311765
Adventure                              4.180822
Adventure;Action & Adventure           4.423077
Adventure;Brain Games                  4.600000
...                                         ...
Video Players & Editors                4.063924
Video Players & Editors;Creativity     4.100000
Video Players & Editors;Music & Video  4.000000
Weather                                4.244000
Word                                   4.410714

[115 rows x 1 columns]